services:
  node:
    hostname: email-opera-node
    container_name: email-opera-node
    image: node:22-bookworm
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: bash -c "npm install && npm run watch"
    ports:
      - "8080:8080"
  php:
    hostname: email-opera-php
    container_name: email-opera-php
    image: php:8.2-fpm-bookworm
    restart: unless-stopped
    working_dir: /var/www/html
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
  nginx:
    hostname: email-opera-nginx
    container_name: email-opera-nginx
    image: nginx:bookworm
    restart: unless-stopped
    working_dir: /var/www/html
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./:/var/www/html
    ports:
      - "80:80"